In [2]:
import pandas as pd
import numpy as np

In [3]:
different_kind_of_adjective_things = pd.read_csv("./data/different_kind_of_adjective_things.csv")
different_kind_of_things = pd.read_csv("./data/different_kind_of_things.csv")
different_kind_of_things_words = pd.read_csv("./data/different_kind_of_things_words.csv")

In [4]:
different_kind_of_adjective_things

,searchString,id,title,createdAt,firstPublishedAt,readingTime,wordCount,totalClapCount
0,1 best thing,9af895217f10,The 1 Best Thing,2016-05-17 10:33:07,2016-05-17 11:04:01,3.931,940,21
1,1 easy thing,f58a0abd1578,Millionaire Entrepreneurs Always Do This 1 Eas...,2017-11-21 20:37:04,2017-11-21 20:54:43,1.453,332,0
2,1 easy lesson,63b452a5ae14,How To Stop Time In 1 Easy Lesson,2016-06-16 20:11:21,2016-06-14 15:16:40,3.942,899,0
3,1 easy idea,8714f9ed165c,Here Is 1 Easy Idea You Can Use To Unlock His ...,2019-03-23 22:54:45,2019-03-23 22:54:46,4.731,1033,0
4,1 easy idea,fc38579a4744,The 1 Easy Idea You Can Use Today…To Unlock Hi...,2019-10-11 21:01:59,2019-10-11 21:02:43,4.591,1031,0
...,...,...,...,...,...,...,...,...
9316,1000 best things,f5817d648013,!Download e-Book Whole Green Catalog 1000 Best...,2019-10-23 20:05:13,2019-10-28 08:01:07,0.653,173,0
9317,1000 best things,81eb4e1cc1d2,Whole Green Catalog 1000 Best Things for You a...,2019-10-21 09:50:21,2019-10-25 22:36:25,0.683,181,0
9318,1000 easy steps,96c2de032acd,How to open a bank account in London in 1000 e...,2018-03-15 01:18:29,2018-03-12 00:46:25,4.315,958,1
9319,1000 best tips,d59ef4ba5c03,DOWNLOAD 1000 best tips for adhd expert answer...,2019-06-26 22:57:13,2019-06-26 22:57:27,0.079,21,0
9320,1000 best tips,95a96040a122,PDF [Download] 1000 Best Tips for ADHD Expert ...,2019-10-10 06:40:20,2019-10-10 06:41:14,1.823,430,0

In [5]:
different_kind_of_things

,searchString,id,title,createdAt,firstPublishedAt,readingTime,wordCount,totalClapCount
0,1 thing,b8fabbe53bbe,The #1 Thing All Happily Married Couples Have ...,2018-11-04 00:58:33,2018-11-04 21:03:07,6.164,1448,15842
1,1 thing,a8f583d522d7,The Reason You’re Not Successful Is Because Yo...,2018-02-27 22:09:35,2018-03-09 13:34:56,2.343,568,16723
2,1 thing,d63ac1f1af2d,How I Beat Procrastination By Doing This 1 Thing,2019-06-03 15:18:09,2019-06-06 19:30:56,3.602,853,10519
3,1 thing,88cbde105983,Want a Happier More Fulfilling Life 75-Year Ha...,2019-03-26 15:33:44,2019-04-25 20:40:59,8.546,2163,8151
4,1 thing,1b2d2cf93c9d,The 1 Thing Nobody Understands About Content C...,2018-06-24 23:15:31,2018-06-24 23:22:21,2.219,535,6898
...,...,...,...,...,...,...,...,...
61591,1001 ways,ea4f5f5c74e6,1001 Ways to do it Wrong,2017-12-28 14:45:17,2017-12-28 15:14:00,2.204,584,22
61592,1001 ways,a4321a5c486a,Download 1001 Ways to Pay for College Practica...,2018-08-27 18:37:45,2018-08-27 18:37:57,1.121,297,0
61593,1001 reasons,72a164ec07a6,i’m nuts bonkers in fact despite the 1001 reas...,2017-10-27 17:45:49,2017-10-27 17:59:06,0.113,30,0
61594,1008 tips,7b2a2a8cd02c,1008 Tips for Better Life — Vastu Gifts,2016-01-27 13:11:50,2016-01-27 13:13:32,0.049,13,0
61595,1010 tricks,b038d221f449,1010 TRICKS ON HOW TO SURVIVE HackTM !,2016-05-10 09:09:23,2016-05-10 10:54:11,2.887,712,1

In [6]:
different_kind_of_things_words

,searchString,id,title,createdAt,firstPublishedAt,readingTime,wordCount,totalClapCount
0,one thing,c58c11ddfce4,The Power Of Doing Only One Thing,2018-04-12 11:02:40,2018-04-20 17:24:33,2.897,666,54621
1,one thing,5a8be91a5346,There’s Only One Thing To Do With Today Seize It,2019-02-07 16:24:06,2019-02-14 23:45:41,9.657,2559,19699
2,one thing,d6a0b352a2cd,Five Steps to Changing Your Life (they boil do...,2018-05-24 18:07:26,2018-05-25 08:27:45,6.447,1607,15036
3,one thing,a49b5a4b89ea,To Live a Meaningful Life Remember This One Thing,2019-10-09 12:00:51,2019-10-16 13:01:02,1.672,390,10089
4,one thing,bc0d45698a0f,The One Thing Nobody Ever Told You About Perso...,2016-11-04 12:40:09,2016-11-07 11:01:02,4.683,1188,2994
...,...,...,...,...,...,...,...,...
22431,twenty reasons,c0be38cf6bd6,Twenty Reasons to Know the Value of Your Company,2019-09-02 07:54:09,2019-09-02 07:54:10,1.706,452,0
22432,twenty reasons,8f48ed301e30,Twenty reasons why Brexit has made learning fo...,2018-10-16 00:00:49,2018-10-16 00:03:32,12.249,2928,0
22433,twenty reasons,51a4c1a20cce,Twenty reasons your law blogs belong outside y...,2016-08-27 01:55:23,2016-08-27 01:55:24,0.355,41,0
22434,twenty reasons,3831ea666af6,Twenty reasons your law blogs belong outside y...,2016-08-27 01:58:16,2016-08-27 01:58:17,0.355,41,0
22435,twenty decisions,c0b95eadedd4,Twenty Decisions a Day,2016-02-07 11:16:17,2016-02-08 02:24:50,1.457,386,1

Check for empty cells:

In [7]:
np.where(pd.isnull(different_kind_of_adjective_things))

(array([], dtype=int64), array([], dtype=int64))

In [8]:
np.where(pd.isnull(different_kind_of_things))

(array([], dtype=int64), array([], dtype=int64))

In [9]:
np.where(pd.isnull(different_kind_of_things_words))

(array([], dtype=int64), array([], dtype=int64))

Merge the dataframes:

In [10]:
frames = [different_kind_of_adjective_things,different_kind_of_things,different_kind_of_things_words]
nthings = pd.concat(frames)
nthings

,searchString,id,title,createdAt,firstPublishedAt,readingTime,wordCount,totalClapCount
0,1 best thing,9af895217f10,The 1 Best Thing,2016-05-17 10:33:07,2016-05-17 11:04:01,3.931,940,21
1,1 easy thing,f58a0abd1578,Millionaire Entrepreneurs Always Do This 1 Eas...,2017-11-21 20:37:04,2017-11-21 20:54:43,1.453,332,0
2,1 easy lesson,63b452a5ae14,How To Stop Time In 1 Easy Lesson,2016-06-16 20:11:21,2016-06-14 15:16:40,3.942,899,0
3,1 easy idea,8714f9ed165c,Here Is 1 Easy Idea You Can Use To Unlock His ...,2019-03-23 22:54:45,2019-03-23 22:54:46,4.731,1033,0
4,1 easy idea,fc38579a4744,The 1 Easy Idea You Can Use Today…To Unlock Hi...,2019-10-11 21:01:59,2019-10-11 21:02:43,4.591,1031,0
...,...,...,...,...,...,...,...,...
22431,twenty reasons,c0be38cf6bd6,Twenty Reasons to Know the Value of Your Company,2019-09-02 07:54:09,2019-09-02 07:54:10,1.706,452,0
22432,twenty reasons,8f48ed301e30,Twenty reasons why Brexit has made learning fo...,2018-10-16 00:00:49,2018-10-16 00:03:32,12.249,2928,0
22433,twenty reasons,51a4c1a20cce,Twenty reasons your law blogs belong outside y...,2016-08-27 01:55:23,2016-08-27 01:55:24,0.355,41,0
22434,twenty reasons,3831ea666af6,Twenty reasons your law blogs belong outside y...,2016-08-27 01:58:16,2016-08-27 01:58:17,0.355,41,0
22435,twenty decisions,c0b95eadedd4,Twenty Decisions a Day,2016-02-07 11:16:17,2016-02-08 02:24:50,1.457,386,1

In [32]:
def showStats(df):
    sizes = df.groupby('searchString', sort=False).size()
    for i, v in sizes.items():
        print('index: ', i, 'value: ', v)

In [34]:
thing='thing'
matchString = '\d ' + thing
things = nthings.loc[nthings['searchString'].str.contains(matchString)]

In [35]:
things

,searchString,id,title,createdAt,firstPublishedAt,readingTime,wordCount,totalClapCount
0,1 thing,b8fabbe53bbe,The #1 Thing All Happily Married Couples Have ...,2018-11-04 00:58:33,2018-11-04 21:03:07,6.164,1448,15842
1,1 thing,a8f583d522d7,The Reason You’re Not Successful Is Because Yo...,2018-02-27 22:09:35,2018-03-09 13:34:56,2.343,568,16723
2,1 thing,d63ac1f1af2d,How I Beat Procrastination By Doing This 1 Thing,2019-06-03 15:18:09,2019-06-06 19:30:56,3.602,853,10519
3,1 thing,88cbde105983,Want a Happier More Fulfilling Life 75-Year Ha...,2019-03-26 15:33:44,2019-04-25 20:40:59,8.546,2163,8151
4,1 thing,1b2d2cf93c9d,The 1 Thing Nobody Understands About Content C...,2018-06-24 23:15:31,2018-06-24 23:22:21,2.219,535,6898
...,...,...,...,...,...,...,...,...
61547,1000 things,2e4bed0f9d38,The Summer of 1000 Things,2016-06-02 03:34:11,2016-06-02 04:41:14,1.525,404,3
61548,1000 things,9e3dd256ed2e,1000 Things,2016-05-18 17:47:17,2016-05-18 17:47:18,0.725,139,0
61549,1000 things,b9fef865b262,Visit Wales — Wales 1000 Things,2017-03-09 10:10:38,2012-09-02 23:58:30,0.249,13,0
61550,1000 things,8b6b6e041e0,1000 Things,2019-03-04 16:46:52,2019-03-04 16:58:11,0.842,223,0
61583,1001 things,f1f35548e5b8,1001 Things That Can Shape the Future of ChatBots,2016-10-28 23:43:57,2016-10-29 03:46:29,9.795,2450,4

In [33]:
showStats(things)

index:  1 thing value:  701
index:  2 things value:  370
index:  3 things value:  838
index:  4 things value:  911
index:  5 things value:  981
index:  6 things value:  923
index:  7 things value:  888
index:  8 things value:  921
index:  9 things value:  857
index:  10 things value:  982
index:  11 things value:  433
index:  12 things value:  599
index:  13 things value:  471
index:  14 things value:  184
index:  15 things value:  636
index:  16 things value:  127
index:  17 things value:  158
index:  18 things value:  131
index:  19 things value:  91
index:  20 things value:  532
index:  21 things value:  172
index:  22 things value:  98
index:  23 things value:  98
index:  24 things value:  76
index:  25 things value:  281
index:  26 things value:  59
index:  27 things value:  63
index:  28 things value:  53
index:  29 things value:  35
index:  30 things value:  225
index:  31 things value:  45
index:  32 things value:  28
index:  33 things value:  37
index:  34 things value:  6
index:  35 things value:  34
index:  36 things value:  22
index:  37 things value:  54
index:  38 things value:  10
index:  39 things value:  14
index:  40 things value:  205
index:  41 things value:  14
index:  42 things value:  12
index:  43 things value:  10
index:  44 things value:  11
index:  45 things value:  21
index:  46 things value:  7
index:  47 things value:  8
index:  48 things value:  8
index:  49 things value:  4
index:  50 things value:  135
index:  51 things value:  8
index:  52 things value:  34
index:  53 things value:  3
index:  54 things value:  2
index:  55 things value:  10
index:  57 things value:  5
index:  58 things value:  2
index:  59 things value:  2
index:  60 things value:  17
index:  61 things value:  3
index:  62 things value:  2
index:  64 things value:  5
index:  65 things value:  4
index:  66 things value:  2
index:  67 things value:  1
index:  68 things value:  2
index:  69 things value:  4
index:  70 things value:  8
index:  71 things value:  1
index:  72 things value:  1
index:  73 things value:  2
index:  74 things value:  3
index:  75 things value:  2
index:  77 things value:  2
index:  79 things value:  1
index:  80 things value:  3
index:  84 things value:  1
index:  85 things value:  4
index:  88 things value:  2
index:  91 things value:  1
index:  92 things value:  1
index:  94 things value:  1
index:  95 things value:  1
index:  97 things value:  29
index:  98 things value:  1
index:  99 things value:  10
index:  100 things value:  254
index:  101 things value:  44
index:  103 things value:  2
index:  105 things value:  1
index:  107 things value:  2
index:  109 things value:  1
index:  110 things value:  2
index:  111 things value:  1
index:  115 things value:  2
index:  125 things value:  1
index:  128 things value:  1
index:  130 things value:  2
index:  144 things value:  1
index:  150 things value:  3
index:  164 things value:  1
index:  179 things value:  1
index:  200 things value:  5
index:  217 things value:  1
index:  230 things value:  1
index:  273 things value:  1
index:  300 things value:  2
index:  320 things value:  1
index:  329 things value:  1
index:  350 things value:  1
index:  365 things value:  15
index:  400 things value:  3
index:  424 things value:  1
index:  465 things value:  1
index:  470 things value:  1
index:  500 things value:  2
index:  538 things value:  1
index:  605 things value:  1
index:  642 things value:  16
index:  677 things value:  1
index:  684 things value:  1
index:  948 things value:  1
index:  1000 things value:  5
index:  1001 things value:  1